// <auto-generated />
using System;
using LoopbackAuthenticationIntegrationPoC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoopbackAuthenticationIntegrationPoC.Migrations
{
    [DbContext(typeof(LoopbackDbContext))]
    partial class LoopbackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("LoopbackAuthenticationIntegrationPoC.Entities.AccessToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Created")
                        .HasColumnName("created")
                        .HasColumnType("REAL");

                    b.Property<string>("Scopes")
                        .HasColumnName("scopes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ttl")
                        .HasColumnName("ttl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnName("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("accesstoken");
                });

            modelBuilder.Entity("LoopbackAuthenticationIntegrationPoC.Entities.Acl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessType")
                        .HasColumnName("accessType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnName("model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Permission")
                        .HasColumnName("permission")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrincipalId")
                        .HasColumnName("principalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrincipalType")
                        .HasColumnName("principalType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Property")
                        .HasColumnName("property")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("acl");
                });

            modelBuilder.Entity("LoopbackAuthenticationIntegrationPoC.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EmailVerified")
                        .HasColumnName("emailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Realm")
                        .HasColumnName("realm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnName("username")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationToken")
                        .HasColumnName("verificationToken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("LoopbackAuthenticationIntegrationPoC.Entities.AccessToken", b =>
                {
                    b.HasOne("LoopbackAuthenticationIntegrationPoC.Entities.User", "User")
                        .WithMany("AccessTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
